import pandas as pd
import numpy as np
import os
from sklearn.preprocessing import MinMaxScaler

from src.features import compute_technical_indicators, OHLC_features


# Project root 
_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load_dataset(raw_file, datasets_dir='datasets_tfg'):
    # Loads a CSV from datasets_tfg and returns a DF with date as index
    # The path is resolved from the project root
    path = os.path.join(_PROJECT_ROOT, datasets_dir, raw_file)
    df = pd.read_csv(path)
    df['date'] = pd.to_datetime(df['date'])
    df.set_index('date', inplace=True)
    return df


def prepare_features(df):
    # From an OHLCV DF, calculates all technical indicators
    # and OHLC features
    # Drops rows with NaN generated by the indicators
    data = df.copy()
    data = compute_technical_indicators(data)
    data = OHLC_features(data)
    data.dropna(inplace=True)
    return data


def split_train_val(df, start_train, end_train, start_val, end_val):
    # Splits the DF into train and val sets
    # Dates can be strings or datetime
    start_train = pd.to_datetime(start_train, dayfirst=True)
    end_train = pd.to_datetime(end_train, dayfirst=True)
    start_val = pd.to_datetime(start_val, dayfirst=True)
    end_val = pd.to_datetime(end_val, dayfirst=True)

    df_train = df.loc[(df.index >= start_train) & (df.index <= end_train)].copy()
    df_val = df.loc[(df.index >= start_val) & (df.index <= end_val)].copy()

    return df_train, df_val


def normalize_dataframe(df, list_columns_to_normalize, feature_range=(0, 1)):
    # Normalizes the given columns using MinMaxScaler
    # Returns the normalized DF and the scaler to apply to the validation set
    df_norm = df.copy()
    scaler = MinMaxScaler(feature_range=feature_range)
    df_norm[list_columns_to_normalize] = scaler.fit_transform(df[list_columns_to_normalize])

    return df_norm, scaler


def normalize_val_with_scaler(df, list_columns_to_normalize, scaler):
    # Applies an already fitted scaler from train to the validation set
    df_norm = df.copy()
    df_norm[list_columns_to_normalize] = scaler.transform(df[list_columns_to_normalize])

    return df_norm


def accumulate_dataframe(df, list_columns_to_accumulate):
    # Accumulates cumsum the given columns, useful for cumulative log-returns
    df_acc = df.copy()
    for column in list_columns_to_accumulate:
        df_acc[column] = df[column].cumsum()

    return df_acc
